FROM adoptopenjdk/openjdk8-openj9:alpine-slim
VOLUME /tmp
ADD upm-0.0.1-SNAPSHOT.jar upm-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","upm-0.0.1-SNAPSHOT.jar"]
